### ISSUE TITLE
Building does not bundle dependencies

### ISSUE THREAD

**Issue by Aasim-A** [caoxiemeihao/vite-electron-plugin#58]
Hey, thanks for making this plugin.
During development, it works fine. However, when building, the resulting code did not bundle the dependencies thus, I was getting module not found error. Is it doing that by design? How would I go about solving this issue?
One note is: I was using dynamic imports in my code.

**Comment by caoxiemeihao** [comment]
Put the npm-package into `dependencies`

**Comment by Aasim-A** [comment]
it's already there

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by Aasim-A** [comment]
https://github.com/Aasim-A/electron-vite-test

**Comment by Canees** [comment]
> https://github.com/Aasim-A/electron-vite-test
> 
> Once you run the executable that was generated, you'll see the error.

A brief look at your example, first vite is not configured correctly, second if you want to bundle dependency packaging, you can use esbuild alone, and finally, the Vite-electron-plugin plugin does not seem to support dynamic loading, it is only suitable for dev mode use.
Refer to the following command:
![image](https://github.com/caoxiemeihao/vite-electron-plugin/assets/40012261/ad7ecee4-9a4d-4971-8fc9-25338e6f5b04)
![image](https://github.com/caoxiemeihao/vite-electron-plugin/assets/40012261/ea269929-3362-4320-81ae-a13507852092)

**Comment by caoxiemeihao** [comment]
`vite-electron-plugin` does not provide bundle capabilities, it is only applicable to build dependencies in `dependencies` into `app.asar`. Maybe [vite-plugin-electron](https://github.com/electron-vite/vite-plugin-electron) is more suitable for you.
